services:
  - type: web
    name: nova-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: RENDER_URL
        sync: false
      - key: MONGO_DB_NAME
        value: nova_ai_bot
      - key: FREE_DAILY_LIMIT
        value: "30"
      - key: PREMIUM_DAILY_LIMIT
        value: "9999"
      - key: PORT
        value: "8443"
